/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTask: typeof import('./src/components/AddTask.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BProgressBar: typeof import('bootstrap-vue-next')['BProgressBar']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Pager: typeof import('./src/components/Pager.vue')['default']
    QueryMenu: typeof import('./src/components/QueryMenu.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RegisterProfile: typeof import('./src/components/RegisterProfile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDetail: typeof import('./src/components/TaskDetail.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
